image: docker
services:
  - "docker:dind"
stages:
- test
- docker_borringssl
- docker_quictls

variables:
    IMAGE_LATEST: dburianov/nginx-aio:latest
    IMAGE_COMMIT: dburianov/nginx-aio:$CI_COMMIT_SHORT_SHA
    CI: 'false'
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

docker_borringssl_build:
    image: docker:latest
    stage: docker_borringssl
#    except:
#      changes:
#        - "README.md"
#        - ".gitlab-ci.yml"
    only:
      refs:
        - master
        - main
#      variables:
#        - $CI_COMMIT_MESSAGE =~ /^Release .*$/
#        - $CI_COMMIT_MESSAGE =~ /^(feat|fix).+ Borringssl .*/
#        - $CI_PIPELINE_SOURCE == "schedule"
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker buildx create --use
        - tag=$(date +%Y%m%d%H%M)
        - docker buildx build
          --platform linux/amd64
          --tag dburianov/nginx-aio:latest
          --tag dburianov/nginx-aio:borringssl-latest
          --tag dburianov/nginx-aio:buildx-latest
          --tag dburianov/nginx-aio:buildx-$tag
          --push
          --progress plain
          .
        - docker logout

docker_quictls_build:
    image: docker:latest
    stage: docker_quictls
#    except:
#      changes:
#        - "README.md"
#        - ".gitlab-ci.yml"
    only:
      refs:
        - master
        - main
#      variables:
#        - $CI_COMMIT_MESSAGE =~ /^Release .*$/
#        - $CI_COMMIT_MESSAGE =~ /^(feat|fix).+ Quictls .*/
#        - $CI_PIPELINE_SOURCE == "schedule"
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker buildx create --use
        - tag=$(date +%Y%m%d%H%M)
        - docker buildx build
          --platform linux/amd64,linux/arm64/v8
          --tag dburianov/nginx-aio:quictls-latest
          --tag dburianov/nginx-aio:quictls-$tag
          --push
          --progress plain
          -f Dockerfile.quictls
          .
        - docker logout

