image: docker
services:
  - "docker:dind"
stages:
- test
- publish
- docker

variables:
    IMAGE_LATEST: dburianov/nginx-aio:latest
    IMAGE_COMMIT: dburianov/nginx-aio:$CI_COMMIT_SHORT_SHA
    CI: 'false'
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

publish_develop:
    image: docker:latest
    stage: publish
#    only:
#        - develop
#    environment: develop
    services:
        - docker:dind
    script:
#        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker buildx build -t $IMAGE_LATEST -t $IMAGE_COMMIT -f Dockerfile ./
        - tag=$(date +%Y%m%d%H%M)
#        - sudo docker buildx build --push --platform linux/amd64 --tag dburianov/nginx-aio:buildx-latest --tag dburianov/nginx-aio:buildx-$tag --push .
        - sudo docker buildx build --push --platform linux/amd64 --tag dburianov/nginx-aio:buildx-latest --tag dburianov/nginx-aio:buildx-$tag .
#        - docker push $IMAGE_LATEST
#        - docker push $IMAGE_COMMIT
