image: docker
services:
  - "docker:dind"
stages:
- test
- publish
- docker

variables:
    IMAGE_LATEST: dburianov/nginx-aio:latest
    IMAGE_COMMIT: dburianov/nginx-aio:$CI_COMMIT_SHORT_SHA
    CI: 'false'
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

docker_build:
    image: docker:latest
    stage: publish
#    only:
#        - develop
#    environment: develop
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        #$CI_REGISTRY
        - docker buildx create --use
#        - docker buildx build -t $IMAGE_LATEST -t $IMAGE_COMMIT -f Dockerfile ./
        - tag=$(date +%Y%m%d%H%M)
        - docker buildx build
          --platform linux/amd64
          --tag dburianov/nginx-aio:latest
          --tag dburianov/nginx-aio:buildx-latest
          --tag dburianov/nginx-aio:buildx-$tag
          --push
          --progress plain
          .
#        - docker buildx build
#          --platform linux/amd64
#          --tag dburianov/nginx-aio:buildx-linux-amd64-latest
#          --tag dburianov/nginx-aio:buildx-linux-amd64-$tag
#          --load
#          --progress plain
#          .
#        - docker buildx build
#          --platform linux/arm64/v8
#          --tag dburianov/nginx-aio:buildx-linux-arm64-v8-latest
#          --tag dburianov/nginx-aio:buildx-linux-arm64-v8-$tag
#          --load
#          --progress plain
#          .
#        - docker buildx build --push --platform linux/amd64,linux/arm64/v8 --tag dburianov/nginx-aio:buildx-latest --tag dburianov/nginx-aio:buildx-$tag .
#        - docker push $IMAGE_LATEST
#        - docker push $IMAGE_COMMIT
#        - docker manifest create --insecure
#            dburianov/nginx-aio:buildx-$tag 
#              dburianov/nginx-aio:buildx-linux-amd64-latest
#              dburianov/nginx-aio:buildx-linux-arm64-v8-$tag
#        - docker manifest push dburianov/nginx-aio:buildx-$tag
        - docker logout

