stages:
- test
- publish
- docker

variables:
    IMAGE_LATEST: $CI_REGISTRY_IMAGE/nginx-aio:latest
    IMAGE_COMMIT: $CI_REGISTRY_IMAGE/nginx-aio:$CI_COMMIT_SHORT_SHA
    CI: 'false'

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

publish_develop:
#    image: docker:latest
    stage: publish
#    only:
#        - develop
#    environment: develop
    services:
        - docker:dind
    script:
#        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - id
        - docker build -t $IMAGE_LATEST -t $IMAGE_COMMIT -f Dockerfile ./
#        - docker push $IMAGE_LATEST
#        - docker push $IMAGE_COMMIT
