image: docker
services:
  - "docker:dind"
stages:
- test
- setvars
- docker_modsecurity
- docker_boringssl
- docker_quictls
- docker_config
- docker_nginx_test

variables:
    IMAGE_LATEST: dburianov/nginx-aio:latest
    IMAGE_COMMIT: dburianov/nginx-aio:$CI_COMMIT_SHORT_SHA
    CI: 'false'
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

setvars-job:
  stage: setvars
  script:
    - echo "BUILD_TAG=$(date +%Y%m%d.%H%M)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

docker_modsecurity_build:
    image: docker:latest
    stage: docker_modsecurity
    except:
      changes:
        - "README.md"
    only:
      refs:
        - master
        - main
      variables:
        - $CI_COMMIT_MESSAGE =~ /^Release .*$/
        - "$CI_COMMIT_MESSAGE =~ /^(feat|fix): .+/"
        - $CI_PIPELINE_SOURCE == "schedule"
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker buildx create --use
        - docker buildx build
          --platform linux/amd64,linux/arm64/v8
          --tag dburianov/modsecurity_rules:latest
          --tag dburianov/modsecurity_rules:$BUILD_TAG
          --push
          --progress plain
          -f Dockerfile.modsecutity_rules
          .
        - docker logout

docker_boringssl_build:
    image: docker:latest
    stage: docker_boringssl
    except:
      changes:
        - "README.md"
#        - ".gitlab-ci.yml"
    only:
      refs:
        - master
        - main
      variables:
        - $CI_COMMIT_MESSAGE =~ /^Release .*$/
        - "$CI_COMMIT_MESSAGE =~ /^(feat|fix): .+/"
        - $CI_PIPELINE_SOURCE == "schedule"
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker buildx create --use
        - docker buildx build
          --platform linux/amd64
          --tag dburianov/nginx-aio:latest
          --tag dburianov/nginx-aio:boringssl-latest
          --tag dburianov/nginx-aio:buildx-latest
          --tag dburianov/nginx-aio:buildx-$BUILD_TAG
          --push
          --progress plain
          -f Dockerfile.boringssl
          .
        - docker logout

docker_quictls_build:
    image: docker:latest
    stage: docker_quictls
    except:
      changes:
        - "README.md"
#        - ".gitlab-ci.yml"
    only:
      refs:
        - master
        - main
      variables:
        - $CI_COMMIT_MESSAGE =~ /^Release .*$/
        - "$CI_COMMIT_MESSAGE =~ /^(feat|fix): .+/"
        - $CI_PIPELINE_SOURCE == "schedule"
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker buildx create --use
        - docker buildx build
          --platform linux/amd64
          --tag dburianov/nginx-aio:quictls-latest
          --tag dburianov/nginx-aio:quictls-$BUILD_TAG
          --push
          --progress plain
          -f Dockerfile.quictls
          .
        - docker logout

docker_quictls_config_build:
    image: docker:latest
    stage: docker_config
    except:
      changes:
        - "README.md"
    only:
      refs:
        - master
        - main
      variables:
        - "$CI_COMMIT_MESSAGE =~ /^Config: .+/"
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker buildx create --use
        - docker buildx build
          --platform linux/amd64
          --tag dburianov/nginx-aio:quictls-latest
          --tag dburianov/nginx-aio:quictls-$BUILD_TAG
          --push
          --progress plain
          -f Dockerfile.quictls.config
          .
        - docker logout

docker_boringssl_config_build:
    image: docker:latest
    stage: docker_config
    except:
      changes:
        - "README.md"
    only:
      refs:
        - master
        - main
      variables:
        - "$CI_COMMIT_MESSAGE =~ /^Config: .+/"
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker buildx create --use
        - docker buildx build
          --platform linux/amd64
          --tag dburianov/nginx-aio:boringssl-latest
          --tag dburianov/nginx-aio:boringssl-$BUILD_TAG
          --push
          --progress plain
          -f Dockerfile.boringssl.config
          .
        - docker logout

docker_nginx_test:
    image: docker:latest
    stage: docker_nginx_test
    except:
      changes:
        - "README.md"
#        - ".gitlab-ci.yml"
    only:
      refs:
        - master
        - main
      variables:
        - "$CI_COMMIT_MESSAGE =~ /^test: .+/"
    services:
        - docker:dind
    script:
        - docker buildx create --use
        - docker buildx build
          --platform linux/amd64
          --tag nginx_test
          --load
          --progress plain
          -f Dockerfile.test
          --build-arg IMAGE=dburianov/nginx-aio:quictls-latest
          .
        - docker buildx rmi $(docker images -q) || exit 0
        - docker buildx build
          --platform linux/amd64
          --tag nginx_test
          --load
          --progress plain
          -f Dockerfile.test
          --build-arg IMAGE=dburianov/nginx-aio:boringssl-latest
          .
        - docker buildx prune
        - docker buildx rm
        - docker buildx rmi $(docker images -q) || exit 0
