FROM dburianov/modsecurity_rules:latest AS modsecurity_rules
FROM dburianov/geoip:latest AS geoip
FROM dburianov/nginx-aio:borringssl-latest AS nginx-release

LABEL maintainer="Dmytro Burianov <dmytro@burianov.net>"
ARG CACHEBUST=0

RUN <<EOT
    mkdir -p /usr/local/nginx/logs \
             /usr/local/nginx/conf.docker/ssl.dh/ \
             /usr/local/nginx/lua.docker \
             /usr/local/nginx/geoip \
             /usr/local/nginx/conf/ \
             /tmp/modsecurity/tmp \
             /tmp/modsecurity/data \
             /tmp/modsecurity/upload \
             /tmp/nginx
    touch /usr/local/nginx/logs/access.log /usr/local/nginx/logs/error.log
    ln -sf /dev/stdout /usr/local/nginx/logs/access.log
    ln -sf /dev/stderr /usr/local/nginx/logs/error.log
EOT

COPY --from=modsecurity_rules /usr/local/modsecurity /usr/local/modsecurity
COPY --from=geoip /geoip /usr/local/nginx/geoip

ADD docker-entrypoint.sh /docker-entrypoint.sh
ADD conf /usr/local/nginx/conf.docker
ADD lua /usr/local/nginx/lua.docker
ADD dhparams* /usr/local/nginx/conf.docker/ssl.dh/
RUN <<EOT
    echo "Configuring libs and copy default configs"
    echo "/usr/local/nginx/lib/" > /etc/ld.so.conf.d/nginx.conf
    echo "/usr/local/curl/lib" > /etc/ld.so.conf.d/curl.conf
    echo "/usr/local/ssl/lib64" > /etc/ld.so.conf.d/openssl.conf
    echo "/usr/local/ssl/lib" >> /etc/ld.so.conf.d/openssl.conf
    ldconfig -v
    cp -rf /usr/local/nginx/conf.docker/* /usr/local/nginx/conf/
EOT

ENV LD_LIBRARY_PATH=/usr/local/ssl/lib:/usr/local/ssl/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/local/curl/bin:/usr/local/ssl/bin:$PATH

EXPOSE 80/tcp 443/tcp 443/udp 1935/tcp

VOLUME ["/usr/local/nginx/conf", "/usr/local/nginx/html", "/usr/local/nginx/lua", "/usr/local/nginx/logs", "/usr/local/nginx/cache"]

STOPSIGNAL SIGQUIT

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]
