ARG IMAGE
FROM $IMAGE AS nginx-test
ENV LD_LIBRARY_PATH=/usr/local/ssl/lib:/usr/local/ssl/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/local/curl/bin:/usr/local/ssl/bin:$PATH

ARG CACHEBUST=0
RUN <<EOT
    set -e
    #/usr/local/ssl/bin/
    openssl version -a
    #/usr/local/ssl/bin/
    openssl list -providers
    curl --version

    mkdir -p /tmp/nginx/conf.d.inc
    echo "worker_processes $(nproc);" | tee /tmp/nginx/conf.d.inc/worker_processes.conf.inc
    export DNS_RESOLVERS="$(cat /etc/resolv.conf | grep nameserver | cut -d' ' -f2 | xargs)"
    echo "resolver ${DNS_RESOLVERS} valid=30s;" | tee /tmp/nginx/conf.d.inc/resolver.conf.inc
    echo "resolver_timeout 5s;" | tee -a /tmp/nginx/conf.d.inc/resolver.conf.inc

    env | sort
    /usr/local/bin/njs -v
    /usr/local/nginx/sbin/nginx -V
    /usr/local/nginx/sbin/nginx -t
EOT
