ARG IMAGE
FROM $IMAGE AS nginx-test
ENV LD_LIBRARY_PATH=/usr/local/ssl/lib:/usr/local/ssl/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/local/curl/bin:/usr/local/ssl/bin:$PATH

ARG CACHEBUST=0
RUN <<EOT
    set -e
#    ldconfig -v
#    ls -la /usr/local/curl/lib/
    #/usr/local/ssl/bin/
    openssl version -a
    #/usr/local/ssl/bin/
    openssl list -providers
    curl --version

    echo "worker_processes $(nproc);" > /tmp/nginx/conf.d.inc/worker_processes.conf.inc
    env | sort
    /usr/local/bin/njs -v
    /usr/local/nginx/sbin/nginx -V
    /usr/local/nginx/sbin/nginx -t
EOT
