#.docker_nginx_test_script: &docker_nginx_test_script
.docker_nginx_test_script:
    image: docker:latest
    stage: docker_nginx_test
    rules:
      - if: ($CI_PIPELINE_SOURCE == 'web' && ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH))
    services:
        - docker:dind
    script:
      - |
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

        echo "docker run -d"
        docker run -d --name nginx_test --rm $DOCKER_REPO:$TAG_SSL-latest

        docker ps --all

        echo "docker container logs nginx_test"
        #a=$(
        docker container logs nginx_test
        # 2>&1 |tee -a /tmp/nginx_test.logs | grep 'test is successful')
        #echo "exit: $a"
        #cat /tmp/nginx_test.logs
        #retVal=$?
        #if [ $retVal -ne 0 ]; then
        #    echo "Error"
        #fi
        #exit $retVal
        docker container stop nginx_test
        echo "docker stop"
